### ISSUE TITLE
createTableIfNotExists always giving error

### ISSUE THREAD

**Issue by cragia** [lookify/cassandrom#1]
Hello.
I'm directly calling cassandrom.connection.model with the table name and the schema, so I'm sure that if the table not exists it creates it.
But I noticed that this always gives back an error (if the table exists), because the query "SELECT table_name FROM system_schema.tables WHERE keyspace_name=?" always gives back 0 results, and I think it's because the table "system_schema.tables" has just a column and it's called "table_name", and not "keyspace_name".

**Comment by kiril-me** [comment]
Can you provide the code how you initialize the model?

It's better not to call cassandrom.connection.model directly. Create the model:
```
// create model
var User = cassandrom.model("User", schema);

// will return the same mode 
var User2 = cassandrom.models.User;
```
Also, the connection is created async; you can use the callback.

**Comment by kiril-me** [comment]
@cragia I released new cassandrom version. Can you verify is it fixed?

**Comment by cragia** [comment]
Ok, the issue now seems to be solved.

thank you! :)
